---
- hosts: all
  become: yes
  tasks:
  - name: Install python3-pip
    apt:
      pkg:
        - python3-pip
        - python3-docker
  - name: Gcloud Configure Docker
    become: yes
    shell: "gcloud --quiet auth configure-docker"
  - name: pull an image
    docker_image:
      name: asia.gcr.io/rise-prod-327008/{{ image_name }}:{{image_tag}}
  - name: Create directory mount if they don't exist
    file:
      path: "{{  item.split(\":\")[0] | lower }}"
      state: directory
      owner: app_user
      mode: 0755
    loop: "{{mount_volume}}"
  - name: Run container
    become: yes
    community.docker.docker_container:
      name: "{{ image_name }}"
      state: started
      restart: yes
      image: "asia.gcr.io/rise-prod-327008/{{ image_name }}:{{image_tag}}"
      ports: "{{node_port}}:{{container_port}}"
      volumes: "{{mount_volume}}"
