---
- hosts: all
  become: yes
  tasks:
  - name: Install python3-pip
    apt:
      pkg:
        - python3-pip
        - python3-docker
  - name: Gcloud Configure Docker
    shell: "gcloud --quiet auth configure-docker"
  - name: Create directory mount if they don't exist
    file:
      path: "{{  item.split(\":\")[0] | lower }}"
      state: directory
      owner: apps_user
      mode: 0755
    loop: "{{mount_volume}}"
  - name: Run container
    community.general.docker_container:
      image: "asia.gcr.io/rise-prod-327008/{{ image_name }}:{{image_tag}}"
      name: "{{ image_name }}:{{image_tag}}"
      state: started
      ports: "{{node_port}}:{{container_port}}"
      volumes: "{{mount_volume}}"
