---
- hosts: all  
  tasks:
  - name: Install java
    become: yes
    apt:
      pkg:
        - openjdk-11-jre
        - openjdk-11-jdk
  - name: Create directory if they don't exist
    become: yes
    file:
      path: "{{ item }}"
      state: directory
      owner: apps_user
      mode: 0755
    loop:
      - /opt/{{app_name}}
      - /opt/{{app_name}}/bin
      - /opt/{{app_name}}/log
      - /opt/{{app_name}}/pid
      - /opt/{{app_name}}/config
  - name: Move jar to bin
    become_user: apps_user
    command: mv ${{ inputs.app-name }}/{{ app_name }}-v{{ app_version }}.jar /opt/{{app_name}}/bin
  - name: Creating a file with content
    become_user: apps_user
    template: src=java.service.j2 dest=/opt/{{app_name}}/pid/{{app_name}}.service mode=644
  - name: Start JavaApp
    become_user: apps_user
    service: name=/opt/{{app_name}}/pid/{{app_name}}.service state=started enabled=yes