---
- hosts: all  
  tasks:
  - name: Install java
    become: yes
    apt:
      pkg:
        - openjdk-11-jre
        - openjdk-11-jdk
  - name: Creating a file with content
    become: apps_user
    template: src=java.service.j2 dest=/etc/systemd/system/{{app_name}}.service mode=644
  - name: JavaApp | Start JavaApp
    become: apps_user
    service: name={{app_name}}.service state=started enabled=yes
