---
- hosts: all  
  tasks:
  - name: Install java
    become: yes
    apt:
      pkg:
        - openjdk-11-jre
        - openjdk-11-jdk
  - name: Create directory if they don't exist
    file:
      path: "{{ item }}"
      state: directory
      owner: apps_user
      mode: 0755
    loop:
      - /opt/{{app_name}}
      - /opt/{{app_name}}/bin
      - /opt/{{app_name}}/log
      - /opt/{{app_name}}/pid
      - /opt/{{app_name}}/config
  - name: check files
    shell: "ls -la /opt/{{app_name}}"
    register: hello
  - debug: var=hello.stdout_lines
  - name: copy jar 
    become: true
    copy:
      src: /tmp/{{ app_name }}-v{{ app_version }}.jar
      dest: /opt/{{app_name}}/bin/{{ app_name }}-v{{ app_version }}.jar
      owner: apps_user     
      mode: 0755
  - name: Creating a service file
    become: true
    ansible.builtin.template:
      src: java.service.j2
      dest: /opt/{{app_name}}/pid/{{app_name}}.service
      owner: apps_user
      mode: 0755
  - name: Start JavaApp
    become: true
    service: name=/opt/{{app_name}}/pid/{{app_name}}.service state=started enabled=yes